# Generated by Django 5.0.4 on 2024-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('nickname', models.CharField(max_length=50)),
                ('mbti', models.CharField(max_length=10)),
            ],
        ),
    ]
